redis: &redis
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: spa_toy_app_production


development: *redis

test:
  adapter: async
